CREATE TABLE `playlist_songs` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `playlist_id` INT,
    `song_id` INT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
    FOREIGN KEY (song_id) REFERENCES song(songID) ON DELETE CASCADE
);
